# Prefect logging config file.
#
# Any config in this file can be set with an env var
# `PREFECT_LOGGING_[PATH]_[TO]_[KEY]=VALUE`
#
# Global logging settings values can be interpolated by setting `key: "{{key}}"`
# (note the quotations and double curly brackets). Note that only keys available
# under `prefect.settings.logging` will be interpolated.

version: 1
disable_existing_loggers: False

formatters:
    simple:
        format: "%(asctime)s.%(msecs)03d | %(message)s"
        datefmt: "%H:%M:%S"

    flow_runs:
        format: "%(asctime)s.%(msecs)03d | %(name)s: %(message)s"
        datefmt: "%H:%M:%S"

    task_runs:
        format: "%(asctime)s.%(msecs)03d | %(name)s: %(message)s"
        datefmt: "%H:%M:%S"

    json:
        class: prefect.utilities.logging.JsonFormatter

filters:
    run_context:
        # Injects run information into a log record
        class: prefect.utilities.logging.RunContextInjector

    # A user could define a custom filter that drops records containing
    # sensitive information

handlers:
    console:
        class: logging.StreamHandler
        level: "{{default_level}}"
        formatter: simple

    console_flow_runs:
        class: logging.StreamHandler
        level: "{{default_level}}"
        formatter: flow_runs

    console_task_runs:
        class: logging.StreamHandler
        level: "{{default_level}}"
        formatter: task_runs

    orion:
        class: prefect.utilities.logging.OrionHandler
        level: "{{default_level}}"
        formatter: json

loggers:
    prefect:
        level: DEBUG
        handlers: [console]
        propagate: no

    prefect.flow_runs:
        level: DEBUG
        handlers: [orion, console_flow_runs]
        filters: [run_context]
        propogate: no
    
    prefect.task_runs:
        level: DEBUG
        handlers: [orion, console_task_runs]
        filters: [run_context]
        propogate: no

    root:
        level: INFO
        handlers: [console]
