version: 1
disable_existing_loggers: False

formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

    flow_run:
        format: "%(asctime)s - %(flow_run_id)s - %(levelname)s - %(message)s"

    json:
        class: prefect.utilities.logging.JsonFormatter

filters:
    run_context:
        # Injects run information into a log record
        class: prefect.utilities.logging.RunContextInjector

    # A user could define a custom filter that drops records containing
    # sensitive information

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    orion:
        class: prefect.utilities.logging.OrionHandler
        level: DEBUG
        formatter: json

loggers:
    prefect:
        level: DEBUG
        handlers: [console]
        propagate: no

    # Only flow run logs are sent to Orion by default
    prefect.flow_run:
        level: DEBUG
        handlers: [orion]
        filters: [run_context]
        propogate: yes
    
    root:
        level: INFO
        handlers: [console]
