image: "python:3.4"

stages:
  - test

formatting:
  stage: test
  image: "python:3.6"
  script:
    - pip install black isort
    - black --check .

# check linting (pylint):
#   stage: test
#   script:
#   - pip install pylint
#   - pylint prefect

tests:
  stage: test
  script:
    - pip install ".[dev]"
    - pytest
