image: "python:3.4"

stages:
  - test

check formatting:
  stage: test
  image: "python:3.6"
  script:
    - pip install black isort
    - black --check .
    - isort --check -vb

check linting:
  stage: test
  script:
  - pip install pylint
  - pylint prefect

run tests:
  stage: test
  script:
    - pip install ".[dev]"
    - pytest
