image: "python:3.4"

stages:
  - test

format:
  stage: test
  image: "python:3.6"
  script:
    - pip install black isort
    - black --check .
    - isort --check

lint:
  stage: test
  script:
  - pip install pylint
  - pylint prefect

test:
  stage: test
  script:
    - pip install ".[dev]"
    - pytest
