image: "python:3.4"

stages:
  - test

check formatting:
  stage: test
  image: "python:3.6"
  script:
    - pip install black
    - black --check .

# check linting (pylint):
#   stage: test
#   script:
#   - pip install pylint
#   - pylint prefect

run tests:
  stage: test
  script:
    - pip install ".[dev]"
    - pytest -v
