site_name: Prefect Orion
repo_url: https://github.com/PrefectHQ/orion
edit_uri: edit/main/docs/
markdown_extensions:
    - codehilite
    - pymdownx.highlight:
        use_pygments: true
    - pymdownx.superfences
theme:
    name: material
    favicon: img/favicon.ico
    features:
        - navigation.tabs
    icon:
        repo: fontawesome/brands/github
    logo: img/logomark-light.svg
    palette:
        primary: blue
plugins:
    - render_swagger
    - search
nav:
    - Home: index.md
    - 'Getting Started':
        - Installation: installation.md
        - Tutorial: tutorial.md
    - Concepts: concepts.md
    - FAQ: faq.md
    - 'API Reference': 
        - Orion REST API: rest-api.md
        - Client API: client-api.md
