# Netlify settings
#
# Other Netlify files:
# - runtime.txt: version of Python to build with
#
# “command” is your build command,
#

[build]
  base    = ""
  publish = "site"
  command = 'pip install git+https://github.com/mkdocstrings/pytkdocs@4b99cbc7192ab4a1093237a1c79fdf8d70c39b6b && pip install -e ".[dev]" && prefect orion build-docs && mkdocs build'
