# Netlify settings
#
# Other Netlify files:
# - runtime.txt: version of Python to build with
#
# “command” is your build command,
#

[build]
base = ""
command = """
pip install --upgrade pip \
&& pip install git+https://${MARVIN_GITHUB_PAT}@github.com/PrefectHQ/mkdocs-material-insiders.git \
&& pip install --upgrade --upgrade-strategy eager  -e ".[dev]" \
&& prefect dev build-docs  \
&& mkdocs build --config-file mkdocs.insiders.yml
"""
publish = "site"
