- name: hello-sun
  flow_location: ./hello_flows.py
  flow_name: hello-sun
- name: hello-moon
  flow_location: ./hello_flows.py
  flow_name: hello-moon
  schedule:
    interval: 360
- name: bad-deployment
  flow_location: ./bad_flow.py