version: 2.1

references:
  workspace_root: &workspace_root /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root


jobs:
  # ----------------------------------
  # Check formatting
  # ----------------------------------

  check_black_formatting:
    docker:
      - image: python:3.6
    steps:
      - checkout

      - run:
          name: Install Black
          command: pip install black

      - run:
          name: Run Black
          command: black --check .

  check_mypy_typing:
    docker:
      - image: python:3.6
    steps:
      - checkout

      - run:
          name: Install mypy
          command: pip install mypy mypy_extensions

      - run:
          name: Run mypy
          command: mypy src/

  check_documentation:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install prefect
          command: pip install -e ".[dev]"

      - run:
          name: Run documentation tests
          command: pytest -rfEsx -k "generate_docs"

  # test a standard install of prefect
  # is importable in python 3.5.2
  # there was a typing bug in 3.5.2 that this attempts to catch
  test-py352-import-prefect:
    docker:
      - image: python:3.5.2

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install vanilla prefect
          command: pip install .

      - run:
          name: Test Prefect imports cleanly
          command: python -c "import prefect"

  # test a standard install of prefect
  # with all requriements pinned to their lowest allowed versions
  # to ensure our requirements.txt file is accurate
  test-lower-prefect:
    docker:
      - image: python:3.5.2

    steps:
      - *attach_workspace
      - checkout
      - setup_remote_docker
      - run:
          name: Install zsh for tests
          command: apt-get update && apt-get install -y zsh

      - run:
          name: Create lower bound requirements file
          command: python lower_bounds.py

      - run:
          name: Install lower bounds
          command: pip install -r lower_requirements.txt

      - run:
          name: Install vanilla prefect
          command: pip install . --no-deps

      - run:
          name: Install testing packages
          command: pip install "pytest==5.0" pytest-cov pytest-env

      - run:
          name: Run tests
          command: pytest -rfEsx --skip-formatting --cov=prefect --cov-report=xml:/tmp/workspace/coverage/lower-coverage.xml .

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - coverage

  # test a standard install of prefect
  # this ensures we correctly capture all ImportError sitautions
  # caused by many package dependency options
  test-vanilla-prefect:
    docker:
      - image: python:3.6

    steps:
      - *attach_workspace
      - checkout
      - setup_remote_docker
      - run:
          name: Install zsh for tests
          command: apt-get update && apt-get install -y zsh

      - run:
          name: Install vanilla prefect
          command: pip install .

      - run:
          name: Install testing packages
          command: pip install "pytest>=4.3,<5.0" pytest-cov pytest-env

      - run:
          name: Run tests
          command: pytest -rfEsx --skip-formatting --cov=prefect --cov-report=xml:/tmp/workspace/coverage/vanilla-coverage.xml .

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - coverage

  # ----------------------------------
  # Run unit tests in Python 3.5-3.7
  # ----------------------------------

  test-35:
    docker:
      - image: python:3.5

    steps:
      - *attach_workspace
      - checkout
      - setup_remote_docker
      - run:
          name: Install zsh for tests
          command: apt-get update && apt-get install -y zsh

      - run:
          name: Install graphviz
          command: apt-get update && apt-get install -y graphviz

      - run:
          name: Install prefect
          command: pip install ".[all_extras]"

      - run:
          name: Run tests
          command: pytest -rfEsx --skip-formatting --cov=prefect --cov-report=xml:/tmp/workspace/coverage/python35-coverage.xml .

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - coverage

  test-36:
    docker:
      - image: python:3.6
    steps:
      - *attach_workspace
      - checkout
      - setup_remote_docker
      - run:
          name: Install zsh for tests
          command: apt-get update && apt-get install -y zsh

      - run:
          name: Install graphviz
          command: apt-get update && apt-get install -y graphviz

      - run:
          name: Install prefect
          command: pip install ".[all_extras]"

      - run:
          name: Run tests
          command: pytest -rfEsx --skip-formatting --cov=prefect --cov-report=xml:/tmp/workspace/coverage/python36-coverage.xml .

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - coverage

  test-37:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install zsh for tests
          command: apt-get update && apt-get install -y zsh

      - run:
          name: Install graphviz
          command: apt-get update && apt-get install -y graphviz

      - run:
          name: Install prefect
          command: pip install ".[all_extras]"

      - run:
          name: Run tests
          command: pytest -rfEsx .

  test-airflow:
    docker:
      - image: continuumio/miniconda3:4.6.14
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install gcc
          command: apt-get update && apt-get install -y gcc

      - run:
          name: Create Airflow conda environment
          command: conda create -n airflow python=3.6 pip -y

      - run:
          name: Install Airflow
          command: source activate airflow && SLUGIFY_USES_TEXT_UNIDECODE=yes pip install apache-airflow flask==1.0.4 && source deactivate

      - run:
          name: Install prefect
          command: pip install ".[all_extras]"

      - run:
          name: Run tests w/ airflow
          command: pytest -rfEsx --airflow --cov=prefect --cov-report=xml:/tmp/workspace/coverage/airflow-coverage.xml .

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - coverage

  upload-coverage:
    docker:
      - image: python:3.6
    steps:
      - *attach_workspace
      - run:
          name: Upload Coverage
          command: bash <(curl -s https://codecov.io/bash) -cF python -s "/tmp/workspace/coverage/"

  build-docker-image:
    docker:
      - image: docker
    parameters:
      python-version:
        type: string
      tag-latest:
        type: boolean
        default: false
    environment:
      PYTHON_VERSION: << parameters.python-version >>
      PYTHON_TAG: python<< parameters.python-version >>
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build image
          command: >-
            docker build 
            --build-arg GIT_SHA=$CIRCLE_SHA1 
            --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
            --build-arg PREFECT_VERSION=$CIRCLE_TAG 
            -t prefecthq/prefect:${CIRCLE_TAG}-${PYTHON_TAG}
            -t prefecthq/prefect:$PYTHON_TAG
            .
      - when:
          condition: << parameters.tag-latest >>
          steps:
            - run:
                name: Tag latest image
                command: |
                  docker tag prefecthq/prefect:${CIRCLE_TAG}-${PYTHON_TAG} prefecthq/prefect:latest
      - run:
          name: Test image
          command: |
            docker run -dit prefecthq/prefect /bin/bash -c 'curl -fL0 https://raw.githubusercontent.com/PrefectHQ/prefect/master/examples/retries_with_mapping.py | python'
      - run:
          name: Push versioned tags
          command: |
            docker login --username  $DOCKER_HUB_USER --password $DOCKER_HUB_PW
            docker push prefecthq/prefect:${CIRCLE_TAG}-${PYTHON_TAG}
            docker push prefecthq/prefect:$PYTHON_TAG
      - when:
          condition: << parameters.tag-latest >>
          steps:
            - run:
                name: Push latest tag
                command: |
                  docker login --username  $DOCKER_HUB_USER --password $DOCKER_HUB_PW
                  docker push prefecthq/prefect:latest

workflows:
  version: 2

  "Run tests":
    jobs:
      - test-35
      - test-36
      - test-37
      - test-lower-prefect
      - test-vanilla-prefect
      - test-py352-import-prefect
      - test-airflow
      - upload-coverage:
          requires:
            - test-35
            - test-36
            - test-vanilla-prefect
            - test-airflow

  "Check code style and docs":
    jobs:
      - check_black_formatting
      - check_mypy_typing
      - check_documentation

  "Build docker images":
    jobs:
      - build-docker-image:
          python-version: "3.5"
          filters:
            branches:
              only: master
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
      - build-docker-image:
          python-version: "3.6"
          filters:
            branches:
              only: master
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
      - build-docker-image:
          python-version: "3.7"
          tag-latest: true
          filters:
            branches:
              only: master
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/