contact_links:

  - name: Ask a question or present an idea 💡
    url: https://github.com/PrefectHQ/prefect/discussions/category_choices
    about: Life, the universe, and everything

  - name: Chat in Slack 💬
    url: https://join.slack.com/t/prefect-community/shared_invite/enQtODQ3MTA2MjI4OTgyLTliYjEyYzljNTc2OThlMDE4YmViYzk3NDU4Y2EzMWZiODM0NmU3NjM0NjIyNWY0MGIxOGQzODMxNDMxYWYyOTE
    about: Don't panic
