# Licensed under the Prefect Community License, available at
# https://www.prefect.io/licenses/prefect-community-license.pdf

[tool.black]
target_version = ['py37']
exclude = '''
    (
        \.eggs
        | \.git
        | \.hg
        | \.mypy_cache
        | \.tox
        | \.venv
        | _build
        | buck-out
        | build
        | dist

        # server-specific
        | node_modules
        | docs
    )
    '''
