# base metadata
name: null
version: null
tags: []
description: null
schedule: null

# flow-specific fields
flow_name: null
path: null
parameters: {}
parameter_openapi_schema: null

# infra-specific fields
work_pool_name: null
work_queue_name: null
infra_overrides: []