version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

    json:
        class: prefect.core.utilities.logging.JsonFormatter

handlers:
    console:
        class: logging.StreamHandler
        level: ${console_level}
        formatter: simple
        stream: ext://sys.stdout

    orion:
        class: prefect.core.utilities.logging.OrionHandler
        level: DEBUG
        formatter: json

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: ${log_directory}/info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8
        delay: True

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: ${log_directory}/errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8
        delay: True

loggers:
    prefect:
        level: ${prefect_level}
        handlers: [console, error_file_handler]
        propagate: no

    # Only flow run logs are sent to Orion by default
    prefect.flow_run:
        level: ${prefect_level}
        handlers: [orion]
        propogate: yes


root:
    level: ${root_level}
    handlers: [console, info_file_handler, error_file_handler]
