name: Build images

on: [pull_request]

jobs:
  build-test-images:
    name: Build test images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.7
          - 3.8
          - 3.9

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            PYTHON_VERSION=${{ matrix.python-version }}
            PREFECT_EXTRAS=[dev]
          tags: prefecthq/prefect:dev-python${{ matrix.python-version }}
          outputs: type=docker,dest=/tmp/image.tar

      - name: Test docker image
        run: |
          docker load --input /tmp/image.tar
          docker run --rm prefecthq/prefect:dev-python${{ matrix.python-version }} prefect version

      - name: Upload image artifact
        uses: actions/upload-artifact@v2
        with:
          name: image-${{ github.sha }}-${{ matrix.python-version }}
          path: /tmp/image.tar
          retention-days: 1