name: Publish Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Publish Documentation
    strategy:
      matrix:
        python-version: [ 3.8 ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install Orion
        run: python3 -m pip install -e ".[dev]"

      - name: Build REST API reference docs
        run: prefect orion build-docs

      - name: Deploy 🚀
        run: python3 -m mkdocs gh-deploy --force
