name: Integration Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: "pip"
          cache-dependency-path: "requirements*.txt"

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --upgrade-strategy eager -e .[dev]
          
      - name: Start orion
        run: |
          prefect orion start &

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache-dependency-path: '**/package-lock.json'

      - name: Install orion-ui dependencies
        working-directory: ./orion-ui
        run: npm ci install

      - name: Build orion-ui
        working-directory: ./orion-ui
        run: npm run build

      - name: Install Playwright Browsers
        working-directory: ./orion-ui
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        working-directory: ./orion-ui
        run: npx playwright test

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: ./orion-ui/playwright-report/
          retention-days: 30
