name: Get debug output from PyPI

on: [pull_request]

jobs:
  debug-pypi:
    strategy:
      fail-fast: false
      matrix:
        include:
          - endpoint: "pypi.org"
            request-route: "/pypi/pip/json"
          - endpoint: "test.pypi.org"
            request-route: "/pypi/pip/json"
          - endpoint: "files.pythonhosted.org"
            request-route: "/packages/ae/e8/2340d46ecadb1692a1e455f13f75e596d4eab3d11a57446f08259dee8f02/pip-10.0.1.tar.gz"

    name: Debug PyPI
    runs-on: ubuntu-latest

    steps:
      - name: "DNS"
        run: |
          dig ${{ matrix.endpoint }} A
          dig ${{ matrix.endpoint }} AAAA

      - name: "Traceroutes"
        run: |
          traceroute ${{ matrix.endpoint }}
          # traceroute6 ${{ matrix.endpoint }}

      - name: "HTTPS requests"
        run: |
          curl -vvv -I --ipv4 https://${{ matrix.endpoint }}${{ matrix.request-route }}
          # curl -vvv -I --ipv6 https://${{ matrix.endpoint }}${{ matrix.request-route }}

      - name: "TLS debug"
        run: |
          echo -n | openssl s_client -4 -connect ${{ matrix.endpoint }}:443
