name: Python static analysis

on:
  pull_request:
    paths:
      - "**/*.py"
      
jobs:
  python-format:
    
    name: Python formatting

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      
      - name: Install black
        run: |
          python -m pip install --upgrade pip
          pip install $(grep black requirements-dev.txt)

      - name: Run black check
        run: |
          black --check src
