name: Release

on:
  push:
    tags:
      - "2.0a[0-9]+"

jobs:
  build-release:
    name: Build Release

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # Versioneer only generates correct versions with a full fetch
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set up Node 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          # Load installed python packages from the cache
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements*.txt') }}
          
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --upgrade-strategy eager -e .[dev]

      - name: Build UI
        run: |
          prefect dev build-ui 

      - name: Build a binary wheel and a source tarball
        run: |
          python setup.py sdist
          python setup.py bdist_wheel

      - name: Publish build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: built-package
          path: './dist'

  build-docker-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.7
          - 3.8
          - 3.9
      max-parallel: 1

    steps:

      # Not needed until we want multiarchecture builds
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Generate image metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: prefecthq/prefect
          tags: |
            type=pep440,pattern={{version}}
            type=pep440,pattern={{major}}.{{minor}}
            type=pep440,pattern={{major}}
            type=sha
          flavor: |
            latest=false
            suffix=-python${{ matrix.python-version }}

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          build-args:
            PYTHON_VERSION=${{ matrix.python-version }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          outputs: type=docker,dest=/tmp/image-${{ matrix.python-version }}.tar
          
      - name: Test docker image
        run: |
          docker load --input /tmp/image-${{ matrix.python-version }}.tar
          docker run --rm prefecthq/prefect:${GITHUB_REF#refs/*/} prefect --version

      - name: Upload image artifact
        uses: actions/upload-artifact@v2
        with:
          name: built-image-${{ matrix.python-version }}
          path: /tmp/image-${{ matrix.python-version }}.tar

  publish-docs:
    name: Open PR to docs branch
    needs: [build-release, publish-test-release]
    environment: 'prod'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Checkout current docs
        run: git checkout docs --

      - name: Create a temporary branch
        # the release tag is parsed from the ref
        run: git checkout -b "docs-for-release-${GITHUB_REF#refs/*/}"

      - name: Merge with main
        run: git merge origin/main --no-ff -m "Merge branch 'main' into temporary docs branch"

      - name: Push and open PR
        run: |
          git push --set-upstream origin HEAD
          gh pr create \
            --title "Publish docs from release ${GITHUB_REF#refs/*/}" \
            --body '_automatically created with `gh` cli on merge to `main`_' \
            --base docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-test-release:
    name: Publish Release to Test PyPI
    needs: [build-release]
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: built-package
          path: './dist'

      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

  publish-code:
    name: Open PR to OS Prefect repo
    environment: 'prod'
    needs: [build-release, publish-test-release]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Configure upstream
        run: git remote add prefect-orion https://${MARVIN_GITHUB_TOKEN}@github.com/PrefectHQ/prefect.git
        env:
          MARVIN_GITHUB_TOKEN: ${{ secrets.OS_GITHUB_TOKEN }}

      - name: Create a temporary branch & merge w/ upstream
        # the release tag is parsed from the ref
        run: |
          git checkout -b "orion-release-${GITHUB_REF#refs/*/}"
          git fetch prefect-orion
          git merge prefect-orion/orion -m "Merge w/ latest upstream changes"

      - name: Push and open PR
        run: |
          git push --set-upstream prefect-orion "orion-release-${GITHUB_REF#refs/*/}"
          gh pr create \
            --title "Publish code from Orion release ${GITHUB_REF#refs/*/}" \
            --body '_automatically created with `gh` cli on merge to `main`_' \
            --base orion --repo prefecthq/prefect

  publish-release:
    name: Publish Release to PyPI
    environment: 'prod'
    needs: [build-release, publish-test-release]
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: built-package
          path: './dist'

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

          name: ci

  publish-docker-images:
    needs: [publish-release, build-docker-images]
    environment: 'prod'

    runs-on: ubuntu-latest
    steps:

      - name: Download image artifacts for Python 3.7
        uses: actions/download-artifact@v2
        with:
          name: built-image-3.7
          path: /tmp

      - name: Download image artifacts for Python 3.8
        uses: actions/download-artifact@v2
        with:
          name: built-image-3.8
          path: /tmp

      - name: Download image artifacts for Python 3.9
        uses: actions/download-artifact@v2
        with:
          name: built-image-3.9
          path: /tmp

      - name: Load images
        run: |
          docker load --input /tmp/image-3.7.tar
          docker load --input /tmp/image-3.8.tar
          docker load --input /tmp/image-3.9.tar

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push images
        run: |
          docker image push --all-tags prefecthq/prefect
