name: Run tests

on: [pull_request]

jobs:
  run-tests:

    strategy:
      matrix:
        python-version:
          - 3.7
          # Testing on all supported Python versions is not necessary yet
          # - 3.8
          # - 3.9
        os: 
          - ubuntu-latest
          # Testing on Windows is not necessary yet
          # - windows-latest
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          # Versioneer only generates correct versions with a full fetch
          # Versioneer is not setup for this repo yet
          # fetch-depth: 0
          persist-credentials: false

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          # Load installed python packages from the cache
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements*.txt') }}
          
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --upgrade-strategy eager -e .[dev]

      - name: Run unit tests
        env: 
          PREFECT_ORION_DATABASE_CONNECTION_URL: "sqlite+aiosqlite:///:memory:"
        run: |
          pytest tests/unit_tests

      - name: Run integration tests
        env: 
          PREFECT_ORION_DATABASE_CONNECTION_URL: "sqlite+aiosqlite:////tmp/orion-tests.db"
        run: |
          pytest tests/integration_tests
