name: Run static analysis

on: [pull_request]

jobs:
  python-typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          # Load installed python packages from the cache
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements*.txt') }}
          
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --upgrade-strategy eager -e .[dev] 

      - name: Run mypy
        run: |
          mypy src

  python-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install black
        run: |
          python -m pip install --upgrade pip
          pip install $(grep black requirements-dev.txt)

      - name: Run black check
        run: |
          black --check src
